//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eczane1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EczaneDataBaseEntities3 : DbContext
    {
        public EczaneDataBaseEntities3()
            : base("name=EczaneDataBaseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_eczane> tbl_eczane { get; set; }
        public virtual DbSet<tbl_eczane_ilac> tbl_eczane_ilac { get; set; }
        public virtual DbSet<tbl_il> tbl_il { get; set; }
        public virtual DbSet<tbl_ilac> tbl_ilac { get; set; }
        public virtual DbSet<tbl_ilac_turu> tbl_ilac_turu { get; set; }
        public virtual DbSet<tbl_ilce> tbl_ilce { get; set; }
        public virtual DbSet<tbl_kullanici> tbl_kullanici { get; set; }
        public virtual DbSet<tbl_mahalle> tbl_mahalle { get; set; }
        public virtual DbSet<tbl_rol> tbl_rol { get; set; }
        public virtual DbSet<tbl_semt> tbl_semt { get; set; }
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Iller> Iller { get; set; }
    
        public virtual ObjectResult<il_ilce_Result> il_ilce(Nullable<int> il_id)
        {
            var il_idParameter = il_id.HasValue ?
                new ObjectParameter("il_id", il_id) :
                new ObjectParameter("il_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<il_ilce_Result>("il_ilce", il_idParameter);
        }
    
        public virtual ObjectResult<il_ilce_semt_Result> il_ilce_semt(Nullable<int> ilce_id)
        {
            var ilce_idParameter = ilce_id.HasValue ?
                new ObjectParameter("ilce_id", ilce_id) :
                new ObjectParameter("ilce_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<il_ilce_semt_Result>("il_ilce_semt", ilce_idParameter);
        }
    
        public virtual ObjectResult<il_ilce_semt_mahalle_Result> il_ilce_semt_mahalle(Nullable<int> semt_id)
        {
            var semt_idParameter = semt_id.HasValue ?
                new ObjectParameter("semt_id", semt_id) :
                new ObjectParameter("semt_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<il_ilce_semt_mahalle_Result>("il_ilce_semt_mahalle", semt_idParameter);
        }
    
        public virtual ObjectResult<mahalle_kodu_tam_adres_Result> mahalle_kodu_tam_adres(Nullable<int> mahalle_id)
        {
            var mahalle_idParameter = mahalle_id.HasValue ?
                new ObjectParameter("mahalle_id", mahalle_id) :
                new ObjectParameter("mahalle_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mahalle_kodu_tam_adres_Result>("mahalle_kodu_tam_adres", mahalle_idParameter);
        }
    }
}
