//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eczane1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ilac()
        {
            this.tbl_eczane_ilac = new HashSet<tbl_eczane_ilac>();
        }
    
        public int ilac_id { get; set; }
        public string ilac_ad { get; set; }
        public int ilac_kod { get; set; }
        public Nullable<decimal> ilac_fiyat { get; set; }
        public Nullable<int> ilac_turu_id { get; set; }
        public Nullable<System.DateTime> ilac_skt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_eczane_ilac> tbl_eczane_ilac { get; set; }
        public virtual tbl_ilac_turu tbl_ilac_turu { get; set; }
    }
}
