//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eczane1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eczane_ilac
    {
        public int eczene_ilac_id { get; set; }
        public int eczane_id { get; set; }
        public int ilac_id { get; set; }
    
        public virtual tbl_eczane tbl_eczane { get; set; }
        public virtual tbl_ilac tbl_ilac { get; set; }
    }
}
