//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eczane1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eczane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_eczane()
        {
            this.tbl_eczane_ilac = new HashSet<tbl_eczane_ilac>();
        }
    
        public int eczane_id { get; set; }
        public string eczane_nickname { get; set; }
        public string eczane_password { get; set; }
        public Nullable<int> eczane_tescil { get; set; }
        public string eczane_ad { get; set; }
        public string eczane_telefon { get; set; }
        public int mahalle_id { get; set; }
        public int rol_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_eczane_ilac> tbl_eczane_ilac { get; set; }
        public virtual tbl_rol tbl_rol { get; set; }
        public virtual tbl_mahalle tbl_mahalle { get; set; }
    }
}
